name: Publish Helm chart

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "charts/**"

env:
  HELM_REP: helm-test
  GH_OWNER: ronahk
  CHART_DIR: charts/idan

jobs:
  publish_chart:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name ronahk
          git config user.email rona@komodor.io
      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.10.0
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: ${{ env.CHART_DIR }}
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
