name: Publish Helm chart

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "charts/**"

env:
  HELM_REP: helm-test
  GH_OWNER: ronahk
  CHART_DIR: charts/idan

jobs:
  publish_chart:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install chart-releaser
        run: |
          wget https://github.com/helm/chart-releaser/releases/download/v1.4.1/chart-releaser_1.4.1_linux_amd64.tar.gz
          echo "96607338be59ba35101e3d8ff8d8cd36db5289ccb992a00b9a161001e26774ae  chart-releaser_1.4.1_linux_amd64.tar.gz" | sha256sum -c -
          tar xzvf chart-releaser_1.4.1_linux_amd64.tar.gz cr
      - name: Package helm chart
        run: |
          ./cr package ${{ env.CHART_DIR }}
      - name: Upload helm chart
        run: |
          ./cr upload -o ${{ env.GH_OWNER }} -r ${{ env.HELM_REP }} --token ${{ secrets.GITHUB_TOKEN }} -p .cr-release-packages --skip-existing
      - name: Index helm chart
        run: |
          ./cr index -o ${{ env.GH_OWNER }} -r ${{ env.HELM_REP }} -c https://${{ env.GH_OWNER }}.github.io/${{ env.HELM_REP }}/ -i index.yaml --push
      - name: Show index.yaml
        run: cat index.yaml
