name: Publish Helm chart

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "charts/**"

# env:
#   HELM_REP: helm-charts
#   GH_OWNER:
#   CHART_DIR: charts/selek

jobs:
  publish_chart:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      # - name: Pushes test folder
      #   uses: datalbry/copy_folder_to_another_repo_action@1.0.0
      #   env:
      #     API_TOKEN_GITHUB: ${{ secrets.ADMIN_KOMI_GITHUB_TOKEN }}
      #   with:
      #     source_folder: 'test_files'
      #     destination_repo: 'dmnemec/release-test'
      #     destination_folder: 'test-dir'
      #     user_email: 'komi@komodor.io'
      #     user_name: 'komodor-bot'
      #     commit_msg: '[GHA] Update the test files.'
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # - name: Run chart-releaser
      #   uses: helm/chart-releaser-action@v1.1.0
      #   env:
      #     CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
