name: release

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get plugin version
        id: version
        run: |
          current=$(cat plugin.yaml | grep "version" | cut -d '"' -f 2)
          next_version=$(semver-cli inc "minor" $current)
          echo "next_version is now $next_version"
          echo "::set-output name=version::$next_version"

  bump_versions:
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update plugin.yaml version
        uses: jossef/action-set-json-field@v1
        with:
          file: plugin.yaml
          field: version
          value: ${{ needs.prepare.outputs.version }}

      - name: Show file
        run: cat plugin.yaml
