name: release

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.17"

      - name: Get plugin version
        id: version
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} > token
          gh auth login --with-token < token
          go install github.com/davidrjonas/semver-cli@latest
          current=$(cat plugin.yaml | grep "version" | cut -d '"' -f 2)
          next_version=$(semver-cli inc "minor" $current)
          echo "next_version is now $next_version"
          echo "::set-output name=version::$next_version"

  bump_versions:
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Update plugin.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: plugin.yaml
          propertyPath: version
          value: ${{ needs.prepare.outputs.version }}
          commitChange: false

      - name: Show file
        run: cat plugin.yaml
